<?php
//require_once APP_R_PROY . 'app/controllers/serviciosController.php';
//require_once APP_R_PROY . 'app/controllers/VerizonImportController.php';
//require_once APP_R_PROY . 'app/controllers/gpsController.php';
                    
//use app\controllers\gpsController;
use app\models\mainModel;
use app\controllers\address_clasController;
use app\controllers\address_typeController;
use app\controllers\areasController;
use app\controllers\clientesController; 
use app\controllers\ciudadesController;
use app\controllers\condadosController;
use app\controllers\contratosController;
use app\controllers\crewController;
use app\controllers\dias_no_actividadController;
use app\controllers\direccionesController;
use app\controllers\estadosController;
use app\controllers\facturacionController;
use app\controllers\frecuencia_servicioController;
use app\controllers\mobilesController;
use app\controllers\route_dayController;
use app\controllers\rutas_mapaController;
use app\controllers\salasController;
use app\controllers\serviciosController;
use app\controllers\status_allController;
use app\controllers\paisesController;
use app\controllers\proveedoresController;
use app\controllers\usuariosController;
use app\controllers\vehiculosController;
use app\controllers\VerizonImportController;
use app\controllers\viewsController;
use app\controllers\zipsController;
use app\controllers\zonasController;

//$gps = new gpsController();
$modelo = new mainModel();
$address_clas = new address_clasController();
$address_type = new address_typeController();
$areas = new areasController();
$clientes = new clientesController();
$ciudades = new ciudadesController();
$condados = new condadosController();
$contratos = new contratosController();
$crew = new crewController();
$dias_no_actividad = new dias_no_actividadController();
$direcciones = new direccionesController();
$estados = new estadosController();
$facturacion = new facturacionController();
$frecuencia_servicio = new frecuencia_servicioController();
$mobiles = new mobilesController();
$route_day = new route_dayController();
$rutas = new rutas_mapaController();
$salas = new salasController();    
$servicios = new serviciosController();
$status = new status_allController();
$paises = new paisesController();
$proveedores = new proveedoresController();
$usuarios = new usuariosController();
$vehiculos = new vehiculosController();
$verizon = new VerizonImportController();
$viewsController = new viewsController();
$zips = new zipsController();
$zonas = new zonasController();